import { Poppins } from "next/font/google";
import "./globals.css";


const popins = Poppins({
  weight: ['300', '400'],
  subsets: ['latin']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-arp="">
      <body className={`bg-[#171D15]  ${popins.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
